# Generated by Django 6.0.5 on 2026-07-11 15:44

import common.validators
import django.core.validators
import django.db.models.deletion
import masters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MasterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_name', models.CharField(blank=True, max_length=150, null=True, verbose_name='İşletme/Dükkan Adı')),
                ('slug', models.SlugField(blank=True, max_length=200, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to=masters.models.master_file_path, validators=[common.validators.validate_image_size, common.validators.validate_image_extension])),
                ('bio', models.TextField(blank=True, max_length=500, null=True, verbose_name='Kısa Tanıtım')),
                ('experience_year', models.PositiveIntegerField(default=0, verbose_name='Deneyim Yılı')),
                ('rating', models.FloatField(default=5.0, validators=[django.core.validators.MinValueValidator(1.0), django.core.validators.MaxValueValidator(5.0)])),
                ('total_jobs', models.PositiveIntegerField(default=0)),
                ('completed_jobs', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_verified', models.BooleanField(db_index=True, default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='services.category')),
                ('district', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='masters', to='locations.district')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='master_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usta Profili',
                'verbose_name_plural': 'Usta Profilleri',
                'ordering': ['sort_order', '-rating', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MasterWorkImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=masters.models.master_file_path, validators=[common.validators.validate_image_size, common.validators.validate_image_extension])),
                ('caption', models.CharField(blank=True, max_length=100)),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio', to='masters.masterprofile')),
            ],
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['slug'], name='masters_mas_slug_c9a9de_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['is_active'], name='masters_mas_is_acti_5bd482_idx'),
        ),
        migrations.AddIndex(
            model_name='masterprofile',
            index=models.Index(fields=['category', 'district'], name='masters_mas_categor_9b65ce_idx'),
        ),
    ]
