# Generated by Django 6.0.5 on 2026-07-11 15:44

import common.validators
import django.core.validators
import django.db.models.deletion
import masters.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('locations', '0001_initial'),
        ('masters', '0001_initial'),
        ('services', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='İş Başlığı')),
                ('description', models.TextField(max_length=1000, verbose_name='İş Açıklaması')),
                ('budget_min', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Minimum Bütçe')),
                ('budget_max', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Maksimum Bütçe')),
                ('work_photos', models.JSONField(blank=True, default=list, verbose_name='İş Fotoğrafları')),
                ('image', models.ImageField(blank=True, null=True, upload_to=masters.models.master_file_path, validators=[common.validators.validate_image_size, common.validators.validate_image_extension])),
                ('status', models.CharField(choices=[('pending', 'Teklif Bekliyor'), ('offer_received', 'Teklif Geldi'), ('matched', 'Usta Seçildi'), ('on_way', 'Usta Yolda'), ('completed', 'Tamamlandı'), ('cancelled', 'İptal Edildi'), ('expired', 'Süresi Doldu')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('assigned_master', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tasks', to='masters.masterprofile')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='services.category')),
                ('district', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to='locations.district')),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owned_jobs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'İş Talebi',
                'verbose_name_plural': 'İş Talepleri',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('note', models.TextField()),
                ('estimated_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('revision_count', models.PositiveSmallIntegerField(default=0)),
                ('status', models.CharField(choices=[('PENDING', 'Beklemede'), ('ACCEPTED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('provider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='given_bids', to=settings.AUTH_USER_MODEL)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bids', to='jobs.job')),
            ],
            options={
                'verbose_name': 'Teklif',
                'verbose_name_plural': 'Teklifler',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Teklif Fiyatı')),
                ('duration_days', models.PositiveIntegerField(default=1, verbose_name='Süre (Gün)')),
                ('message', models.TextField(max_length=500, verbose_name='Usta Mesajı')),
                ('score', models.FloatField(db_index=True, default=0.0)),
                ('is_accepted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='jobs.job')),
                ('master', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_offers', to='masters.masterprofile')),
            ],
            options={
                'verbose_name': 'İş Teklifi',
                'verbose_name_plural': 'İş Teklifleri',
                'ordering': ['-score', 'price'],
            },
        ),
        migrations.AddIndex(
            model_name='job',
            index=models.Index(fields=['status', 'created_at'], name='jobs_job_status_277b31_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bid',
            unique_together={('job', 'provider')},
        ),
        migrations.AlterUniqueTogether(
            name='joboffer',
            unique_together={('job', 'master')},
        ),
    ]
