# Generated by Django 6.0.5 on 2026-07-11 15:44

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, db_index=True, max_length=254, null=True, unique=True, verbose_name='E-posta')),
                ('full_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Ad Soyad')),
                ('role', models.CharField(blank=True, choices=[('ADMIN', 'Yönetici')], db_index=True, max_length=10, null=True, verbose_name='Rol')),
                ('is_provider', models.BooleanField(default=False, verbose_name='Hizmet Sağlayıcı mı?')),
                ('provider_title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Usta Başlığı')),
                ('bio', models.TextField(blank=True, null=True, verbose_name='Hakkımda')),
                ('avatar_url', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('certificate_url', models.FileField(blank=True, null=True, upload_to='certificates/', verbose_name='Usta Belgesi')),
                ('work_photos', models.JSONField(blank=True, default=list, verbose_name='İş Fotoğrafları')),
                ('trust_score', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Güven Skoru')),
                ('is_face_verified', models.BooleanField(default=False, verbose_name='Yüz Doğrulandı mı?')),
                ('weekly_bid_count', models.IntegerField(default=0, verbose_name='Haftalık Teklif Sayısı')),
                ('weekly_bid_reset_at', models.DateTimeField(blank=True, null=True)),
                ('categories', models.JSONField(blank=True, null=True, verbose_name='Uzmanlık Kategorileri')),
                ('locations_served', models.JSONField(blank=True, null=True, verbose_name='Hizmet Bölgeleri')),
                ('is_approved', models.BooleanField(db_index=True, default=False, verbose_name='Onaylı mı?')),
                ('is_email_verified', models.BooleanField(db_index=True, default=False, verbose_name='E-posta Doğrulandı')),
                ('is_banned', models.BooleanField(db_index=True, default=False, verbose_name='Yasaklı mı?')),
                ('verification_code', models.CharField(blank=True, max_length=6, null=True)),
                ('verification_code_created_at', models.DateTimeField(blank=True, null=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Kullanıcı',
                'verbose_name_plural': 'Kullanıcılar',
                'ordering': ['-date_joined'],
                'indexes': [models.Index(fields=['phone', 'role', 'is_banned', 'is_deleted'], name='accounts_us_phone_4872d4_idx')],
            },
        ),
    ]
