# Generated by Django 6.0.5 on 2026-07-11 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Yönetici'), ('MASTER', 'Usta'), ('USER', 'Müşteri')], db_index=True, default='USER', max_length=10, verbose_name='Rol'),
        ),
    ]
