# Generated by Django 6.0.5 on 2026-07-11 15:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Kategori Adı')),
                ('slug', models.SlugField(blank=True, max_length=120, unique=True)),
                ('icon_name', models.CharField(blank=True, help_text="Örn: 'hammer', 'paint-bucket', 'zap'", max_length=50, null=True, verbose_name='İkon Adı')),
                ('description', models.TextField(blank=True, verbose_name='Kategori Açıklaması')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Sıralama')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='services.category', verbose_name='Üst Kategori')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
                'ordering': ['order', 'name'],
            },
        ),
    ]
